// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvwsahhtpfpuxywrkikx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52d3NhaGh0cGZwdXh5d3JraWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzAyOTcsImV4cCI6MjA2OTkwNjI5N30.ZTQBcFrgSRQ2FDj4iLmrxDzyb2g5E6ZJ3FMMiQaPFkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});